### PR TITLE
first pass at upgrading to Rails 4.2.x

### PR DESCRIPTION
**Pull request by walterdavis**
Please give this a look-over, and compare to the equivalent changes in 1.5.6 -> 1.5.6.1 here: https://github.com/rsim/oracle-enhanced/compare/release15...PMACS:v1.5.6.1

The following chunk is missing: 
pastedgraphic-1

because I cannot figure out where it should go. If anyone can guide me, I would be endlessly appreciative.

### CODE REVIEW

**Comment by emolayi** [comment]
This looks good to me so far - I am looking at the current structure to hopefully find an answer to your question.

**Comment by walterdavis** [comment]
I think I found it, but now I need to know how to install it locally (or use it from vendor or whatever) so I can test it without building and installing it on the server.

**Comment by barendt** [comment]
@walterdavis @emolayi 

Is this ready to merge and install? If so, I'll do that now.

**Comment by walterdavis** [comment]
I can't proofread my own work. Elika? What say you?

**Pull request merged**
